esphome:
  name: ac-planta-sbl

esp8266:
  board: nodemcuv2

logger:
  # level: DEBUG
  level: WARN

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  reboot_timeout: 0s

  ap:
    ssid: "Temperatura SBL"
    password: !secret ap_password
    ap_timeout: 90s

captive_portal:

  # ////////////////////////////////////////////////////////////////////////

# -------- HTTP --------
http_request:
  useragent: esphome/nodemcu
  timeout: 2s
  verify_ssl: false
  id: http_request_sbl

# -------- TIME --------
time:
  - platform: sntp
    id: esptime
    timezone: "America/Bogota"

#---------- LED ESTADO WIFI -----------
output:
  - platform: gpio
    pin:
      number: 16
    id: wifi_led

light:
  - platform: binary
    output: wifi_led
    id: wifi_led_light

# -------- PINES AC PLANTA --------
binary_sensor:
  - platform: gpio
    pin:
      number: 12
      mode: INPUT_PULLUP
    id: ac_pin
    name: "AC Estado"
    on_state:
      then:
        - lambda: |-
            id(ac_estado) = id(ac_pin).state ? 1 : 0;
            id(actualizar_firebase).execute();

  - platform: gpio
    pin:
      number: 4
      mode: INPUT_PULLUP
    id: planta_pin
    name: "Planta Estado"
    on_press: # Cuando enciende
      then:
        - lambda: |-
            id(planta_estado) = 1;
            auto now = id(esptime).now();
            id(engine_start_timestamp) = (uint64_t) now.timestamp * 1000;
            id(engine_stop_timestamp) = 0;
            id(actualizar_firebase).execute();
    on_release: # Cuando apaga
      then:
        - lambda: |-
            id(planta_estado) = 0;
            auto now = id(esptime).now();
            id(engine_stop_timestamp) = (uint64_t) now.timestamp * 1000;
            id(actualizar_firebase).execute();

# -------- VARIABLES --------
globals:
  - id: ac_estado
    type: int
    restore_value: yes
    initial_value: "0"

  - id: planta_estado
    type: int
    restore_value: yes
    initial_value: "0"

  - id: engine_start_timestamp
    type: uint64_t
    restore_value: no
    initial_value: "0"

  - id: engine_stop_timestamp
    type: uint64_t
    restore_value: no
    initial_value: "0"

# -------- SCRIPT FIREBASE --------
script:
  - id: actualizar_firebase
    mode: restart
    then:
      - if:
          condition:
            wifi.connected:
          then:
            - http_request.send:
                id: http_request_sbl
                method: PATCH
                url: !secret firebase_monitoreo_energia
                request_headers:
                  Content-Type: application/json
                body: !lambda |-
                  char buffer[256];
                  sprintf(
                    buffer,
                    "{\"Ac\":%d,\"Planta\":%d,\"engineStartTimestamp\":%llu,\"engineStopTimestamp\":%llu}",
                    id(ac_estado),
                    id(planta_estado),
                    id(engine_start_timestamp),
                    id(engine_stop_timestamp)
                  );
                  return std::string(buffer);

  - id: led_blink_ap
    mode: restart 
    then:
      - while:
          condition:
            wifi.ap_active:
          then:
            - light.toggle: wifi_led_light
            - delay: 500ms
            - lambda: yield();

  # -------- LED INTELIGENTE ESTADO WIFI --------
interval:
  - interval: 5s 
    then:
      - if:
          condition:
            wifi.ap_active:
          then:
            - script.execute: led_blink_ap
          else:
            - script.stop: led_blink_ap
            - if:
                condition:
                  wifi.connected:
                then:
                  - light.turn_on: wifi_led_light
                else:
                  - light.turn_off: wifi_led_light

  # -------- ENVÍO A FIREBASE HEARTBEAT (SIGUE VIVO) --------
  - interval: 60s
    then:
      - if:
          condition:
            wifi.connected:
          then:
            - http_request.send:
                id: http_request_sbl
                method: PATCH
                url: !secret firebase_sala_sb_heartbeat
                request_headers:
                  Content-Type: application/json
                body: '{"timestamp":{".sv":"timestamp"}}'